[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true
minify = "on_release"

[watch]
watch = ["src", "index.html", "style.css"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = true

[clean]
cargo = false
